<!DOCTYPE html>
<html>
<head>
</head>
<body style="font-family: verdana, sans-serif;font-size: 12px;color: #494c4e;">
<p>CC = gcc<br>CCFLAGS = -O3<br>LDFLAGS = -lm</p>
<p>all: mmc&nbsp;</p>
<p>mmc: main.o mm.o<br>&nbsp; &nbsp; $(CC) -o $@ $^ $(LDFLAGS)<br>##$(CC) -o mmc main.o mm.o $(LDFLAGS) &nbsp; &nbsp;&nbsp;</p>
<p>mm.o: mm.c<br>&nbsp; &nbsp; $(CC) -c $(CCFLAGS) $&lt;<br>##$(CC) -c $(CCFLAGS) mm.c</p>
<p>main.o: main.c<br>&nbsp; &nbsp; $(CC) -c $(CCFLAGS) $&lt;<br>##$(CC) -c $(CCFLAGS) main.c</p>
<p>clean:<br>&nbsp; &nbsp; rm *.o &nbsp;</p>
</body>
</html>